services:
  nuxt-app:
    build: ./nuxt-app
    container_name: new-ipsum-nuxt-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    volumes:
      - ./nuxt-app:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: new-ipsum-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo_ui
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URI}